name: 'Maven Build'
description: 'Maven build'
inputs:
  build-env:
    description: 'maven build for what env'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - env:
      MAVEN_USERNAME: ${{ secrets.CVP_MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.CVP_MAVEN_PASSWORD }}
    - if: ${{ inputs.build-env != '' }}
      run: mvn -s settings.xml clean install -P${{ inputs.build-env }}
      shell: bash
    - run: mvn -s settings.xml clean install -P
      shell: bash