name: Test Common Release Workflow

on:
  workflow_call:
    inputs:
      build-env:
        required: true
        type: string

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Test invoke Build action
    steps:
      - uses: actions/checkout@v2
      - uses: ./build@v8
        with:
          build-env: ${{ inputs.build-env }}
      - run: echo "Test common release end"
        shell: bash